# Generated by Django 2.1.1 on 2018-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=120)),
                ('location', models.TextField(default='mylocationdefault', max_length=100)),
                ('job', models.TextField(blank=True, max_length=120)),
            ],
        ),
    ]
