# Generated by Django 2.1.1 on 2018-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='titledeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_name', models.CharField(max_length=30)),
                ('ref_no', models.CharField(max_length=25)),
                ('demographic', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
    ]
